// =====================================================================
// TARJETAS DE REPASO — EN C1 (el curso está en course.js)
// ---------------------------------------------------------------------
// Para añadir tarjetas: copia una línea del mismo tipo y cambia el id
// (debe ser único). *palabra* se muestra en negrita.
// Campos: id, cat, q (instrucción), front (pregunta), back (respuesta),
//         note (explicación opcional).
// =====================================================================

const CATEGORIES = [
  { id: 'ff',   name: 'False friends',     icon: '⚠️' },
  { id: 'err',  name: 'Errores típicos',   icon: '🩹' },
  { id: 'col',  name: 'Collocations',      icon: '🧩' },
  { id: 'pv',   name: 'Phrasal verbs',     icon: '🔗' },
  { id: 'link', name: 'Linkers & tone',    icon: '🪢' },
  { id: 'gram', name: 'Gramática C1',      icon: '🏗️' },
  { id: 'work', name: 'Work English',      icon: '💼' },
  { id: 'vocab', name: 'Vocabulario curso', icon: '📚' },
  { id: 'mine', name: 'Mis frases y fallos', icon: '📝' },
];

const Q = {
  ff:   'What does the word in bold mean here?',
  err:  'Find and fix the mistake.',
  col:  'Complete the collocation.',
  pv:   'Replace the words in brackets with a phrasal verb.',
  link: 'Complete or rephrase it (C1 style).',
  gram: 'Rewrite the sentence as shown.',
  work: 'How would you say this professionally?',
};

const DECK = [
  // ---------- FALSE FRIENDS ----------
  { id: 'ff01', cat: 'ff', front: '*Actually*, I\'ve never been to London.', back: '*Actually* = in fact / to tell the truth.', note: '≠ actualmente → *currently*, *at the moment*.' },
  { id: 'ff02', cat: 'ff', front: 'After months of searching, he *eventually* found a job.', back: '*Eventually* = in the end, after a long time.', note: '≠ eventualmente → *possibly*, *occasionally*.' },
  { id: 'ff03', cat: 'ff', front: 'Can I *assist* you with your luggage?', back: '*Assist* = help.', note: '≠ asistir a una reunión → *attend* a meeting.' },
  { id: 'ff04', cat: 'ff', front: 'That\'s a very *sensible* decision.', back: '*Sensible* = reasonable, practical, showing good judgement.', note: '≠ sensible → *sensitive*.' },
  { id: 'ff05', cat: 'ff', front: 'I was so *embarrassed* when I forgot her name.', back: '*Embarrassed* = feeling uncomfortable or ashamed.', note: '≠ embarazada → *pregnant*.' },
  { id: 'ff06', cat: 'ff', front: 'I think I\'m *constipated*.', back: '*Constipated* = unable to empty your bowels easily.', note: '≠ constipado → *I have a cold*.' },
  { id: 'ff07', cat: 'ff', front: 'Put the documents in the blue *folder*, not on the *carpet*.', back: '*Carpet* = soft covering for the floor.', note: 'carpeta → *folder*.' },
  { id: 'ff08', cat: 'ff', front: 'I usually study at the *library*.', back: '*Library* = place where you borrow books.', note: '≠ librería → *bookshop* (UK) / *bookstore* (US).' },
  { id: 'ff09', cat: 'ff', front: 'I didn\'t *realise* it was so late.', back: '*Realise* = become aware of something.', note: '≠ realizar → *carry out*, *do*, *make*.' },
  { id: 'ff10', cat: 'ff', front: 'He *pretended* to be busy.', back: '*Pretend* = act as if something is true when it isn\'t.', note: '≠ pretender → *intend*, *aim to*.' },
  { id: 'ff11', cat: 'ff', front: 'Use the emergency *exit*.', back: '*Exit* = the way out.', note: '≠ éxito → *success*.' },
  { id: 'ff12', cat: 'ff', front: 'This shirt is made of a soft *fabric*.', back: '*Fabric* = cloth, material.', note: '≠ fábrica → *factory*.' },
  { id: 'ff13', cat: 'ff', front: 'She wants a *career* in finance.', back: '*Career* = your professional path over many years.', note: '≠ carrera universitaria → *degree*.' },
  { id: 'ff14', cat: 'ff', front: 'Can you give me some *advice*?', back: '*Advice* = a suggestion about what to do (uncountable).', note: '≠ aviso → *warning*, *notice*.' },
  { id: 'ff15', cat: 'ff', front: 'The *lecture* starts at 10.', back: '*Lecture* = a formal talk, especially at university.', note: '≠ lectura → *reading*.' },
  { id: 'ff16', cat: 'ff', front: 'We *discussed* the budget in the meeting.', back: '*Discuss* = talk about something calmly.', note: '≠ discutir (pelear) → *argue*.' },
  { id: 'ff17', cat: 'ff', front: 'Oil is a global *commodity*.', back: '*Commodity* = a product that is bought and sold, e.g. oil, coffee.', note: '≠ comodidad → *comfort*, *convenience*.' },
  { id: 'ff18', cat: 'ff', front: 'After hours of talks, they reached a *compromise*.', back: '*Compromise* = an agreement where both sides give something up.', note: '≠ compromiso → *commitment*.' },
  { id: 'ff19', cat: 'ff', front: 'You did a *terrific* job!', back: '*Terrific* = excellent, great.', note: '≠ terrorífico → *terrifying*.' },
  { id: 'ff20', cat: 'ff', front: 'Sorry to *bother* you, but…', back: '*Bother* = annoy, disturb.', note: '⚠️ Never say *molest* for molestar: it means to abuse someone sexually.' },
  { id: 'ff21', cat: 'ff', front: 'What a *coincidence*! I was just thinking about you.', back: '*Coincidence* = two things happening by chance at the same time.', note: 'casualidad → *coincidence*. *Casualty* = victim of an accident or war.' },
  { id: 'ff22', cat: 'ff', front: 'This food contains no *preservatives*.', back: '*Preservative* = chemical that keeps food fresh.', note: '≠ preservativo → *condom*.' },
  { id: 'ff23', cat: 'ff', front: 'The results were a big *disappointment*.', back: '*Disappointment* = sadness because something wasn\'t as good as expected.', note: 'decepción → *disappointment*. *Deception* = engaño.' },
  { id: 'ff24', cat: 'ff', front: 'Let me *introduce* you to my manager.', back: '*Introduce* = present one person to another.', note: '≠ introducir (meter) → *insert*, *put in*.' },
  { id: 'ff25', cat: 'ff', front: 'We need a *large* room for the event.', back: '*Large* = big.', note: '≠ largo → *long*.' },
  { id: 'ff26', cat: 'ff', front: 'Did you *notice* the mistake?', back: '*Notice* = see or become aware of something.', note: '≠ noticia → *news* (uncountable).' },
  { id: 'ff27', cat: 'ff', front: 'She was very *sympathetic* when I lost my job.', back: '*Sympathetic* = showing understanding and care.', note: '≠ simpático → *nice*, *friendly*.' },
  { id: 'ff28', cat: 'ff', front: 'The meeting will *resume* after lunch.', back: '*Resume* = start again after a pause.', note: '≠ resumir → *summarise*.' },
  { id: 'ff29', cat: 'ff', front: 'I can\'t *stand* his attitude.', back: '*Can\'t stand* = can\'t tolerate.', note: 'soportar → *stand*, *put up with*. *Support* = apoyar.' },
  { id: 'ff30', cat: 'ff', front: 'Please *remove* your shoes.', back: '*Remove* = take away / take off.', note: '≠ remover → *stir*.' },
  { id: 'ff31', cat: 'ff', front: 'I *attended* a conference in Madrid.', back: '*Attend* = go to an event, class or meeting.', note: '≠ atender (a un cliente) → *serve*, *deal with*.' },
  { id: 'ff32', cat: 'ff', front: 'We need to *record* the meeting.', back: '*Record* = save sound or video / write down.', note: '≠ recordar → *remember*, *remind*.' },
  { id: 'ff33', cat: 'ff', front: 'It\'s *quite* expensive.', back: '*Quite* (UK) = fairly, rather — not "very".', note: 'quite ≠ bastante siempre: *quite good* suele ser "está bien", no "muy bien".' },

  // ---------- ERRORES TÍPICOS (ES/CAT) ----------
  { id: 'er01', cat: 'err', front: 'I have 30 years.', back: 'I\'m 30 (years old).', note: 'Use *be* for age.' },
  { id: 'er02', cat: 'err', front: 'Is raining again.', back: '*It\'s* raining again.', note: 'English always needs a subject. Use *it* for weather and time.' },
  { id: 'er03', cat: 'err', front: 'The people is very friendly here.', back: 'The people *are* very friendly here.', note: '*People* is plural.' },
  { id: 'er04', cat: 'err', front: 'Can you explain me the problem?', back: 'Can you explain the problem *to me*?', note: 'explain something *to* someone.' },
  { id: 'er05', cat: 'err', front: 'I am agree with you.', back: 'I *agree* with you.', note: '*Agree* is a verb, not an adjective.' },
  { id: 'er06', cat: 'err', front: 'I live in Barcelona since 2015.', back: 'I\'*ve lived* / I\'*ve been living* in Barcelona since 2015.', note: 'Action from the past until now → present perfect.' },
  { id: 'er07', cat: 'err', front: 'I have seen him yesterday.', back: 'I *saw* him yesterday.', note: 'Finished time (yesterday, last week, in 2020) → past simple.' },
  { id: 'er08', cat: 'err', front: 'She said me that she was tired.', back: 'She *told me* that she was tired.', note: '*tell* someone / *say* something (to someone).' },
  { id: 'er09', cat: 'err', front: 'I\'m working here for three years.', back: 'I\'*ve been working* here for three years.', note: 'Duration until now → present perfect continuous.' },
  { id: 'er10', cat: 'err', front: 'It depends of the budget.', back: 'It depends *on* the budget.', note: 'depend *on*.' },
  { id: 'er11', cat: 'err', front: 'I\'m very interesting in the position.', back: 'I\'m very *interested* in the position.', note: '-ed = how you feel; -ing = what causes the feeling.' },
  { id: 'er12', cat: 'err', front: 'We discussed about the budget.', back: 'We *discussed* the budget.', note: '*Discuss* takes no preposition. (But: *talk about*.)' },
  { id: 'er13', cat: 'err', front: 'I have a lot of works to do.', back: 'I have a lot of *work* to do.', note: '*Work* (tasks) is uncountable.' },
  { id: 'er14', cat: 'err', front: 'Can you give me an advice?', back: 'Can you give me *some advice* / *a piece of advice*?', note: '*Advice*, *information*, *news*, *feedback* are uncountable.' },
  { id: 'er15', cat: 'err', front: 'He doesn\'t know nothing.', back: 'He doesn\'t know *anything*. / He knows *nothing*.', note: 'Only one negative per clause in standard English.' },
  { id: 'er16', cat: 'err', front: 'I go to the work by car.', back: 'I go to *work* by car.', note: 'No article: go to work / school / bed / hospital.' },
  { id: 'er17', cat: 'err', front: 'The life is complicated.', back: '*Life* is complicated.', note: 'No *the* with general abstract nouns.' },
  { id: 'er18', cat: 'err', front: 'I want that you come to the meeting.', back: 'I want *you to come* to the meeting.', note: 'want + person + *to* + verb.' },
  { id: 'er19', cat: 'err', front: 'If I will have time, I will call you.', back: 'If I *have* time, I\'ll call you.', note: 'No *will* after *if* / *when* for the future.' },
  { id: 'er20', cat: 'err', front: 'There are much problems.', back: 'There are *many* problems.', note: '*many* + countable; *much* + uncountable.' },
  { id: 'er21', cat: 'err', front: 'I\'m used to work late.', back: 'I\'m used to *working* late.', note: '*be used to* + -ing = be accustomed to.' },
  { id: 'er22', cat: 'err', front: 'Yesterday I went to home early.', back: 'Yesterday I went *home* early.', note: 'No *to* before *home*.' },
  { id: 'er23', cat: 'err', front: 'She\'s more tall than me.', back: 'She\'s *taller* than me.', note: 'Short adjectives: -er.' },
  { id: 'er24', cat: 'err', front: 'I look forward to hear from you.', back: 'I look forward to *hearing* from you.', note: 'Here *to* is a preposition → -ing.' },
  { id: 'er25', cat: 'err', front: 'How is called this in English?', back: '*What is this called* in English?', note: 'What + be + subject + called?' },
  { id: 'er26', cat: 'err', front: 'I didn\'t went to the meeting.', back: 'I didn\'t *go* to the meeting.', note: 'After *didn\'t* → base form.' },
  { id: 'er27', cat: 'err', front: 'My boss let me to leave early.', back: 'My boss let me *leave* early.', note: '*let* / *make* + person + base form (no *to*).' },
  { id: 'er28', cat: 'err', front: 'I\'m boring in these meetings.', back: 'I\'m *bored* in these meetings.', note: 'I\'m boring = los demás se aburren contigo 😅.' },
  { id: 'er29', cat: 'err', front: 'We arrived to the office at 9.', back: 'We arrived *at* the office at 9.', note: 'arrive *at* (a place) / *in* (a city or country).' },
  { id: 'er30', cat: 'err', front: 'It\'s the first time I come here.', back: 'It\'s the first time I\'*ve been* here.', note: 'It\'s the first time + present perfect.' },
  { id: 'er31', cat: 'err', front: 'Although it was late, but we continued.', back: 'Although it was late, we continued.', note: 'Use *although* OR *but*, not both.' },
  { id: 'er32', cat: 'err', front: 'Everybody have a copy.', back: 'Everybody *has* a copy.', note: '*Everybody*, *everyone*, *nobody* take a singular verb.' },
  { id: 'er33', cat: 'err', front: 'Can you make me a favour?', back: 'Can you *do* me a favour?', note: '*do* a favour, *do* business, *do* research.' },
  { id: 'er34', cat: 'err', front: 'I have hungry.', back: 'I\'*m* hungry.', note: '*be* hungry / thirsty / cold / hot / right / afraid.' },
  { id: 'er35', cat: 'err', front: 'I need to do a decision.', back: 'I need to *make* a decision.', note: '*make* a decision / a mistake / an effort / progress.' },

  // ---------- COLLOCATIONS ----------
  { id: 'co01', cat: 'col', front: 'She ___ a presentation to the board.', back: 'She *gave* a presentation to the board.', note: 'give / deliver a presentation.' },
  { id: 'co02', cat: 'col', front: 'The new policy will ___ a significant impact on sales.', back: 'The new policy will *have* a significant impact on sales.' },
  { id: 'co03', cat: 'col', front: 'I\'d like to ___ a concern about the contract.', back: 'I\'d like to *raise* a concern about the contract.', note: 'raise a concern / an issue / a question.' },
  { id: 'co04', cat: 'col', front: 'We\'re ___ progress, but slowly.', back: 'We\'re *making* progress, but slowly.' },
  { id: 'co05', cat: 'col', front: 'The team ___ the deadline despite the problems.', back: 'The team *met* the deadline despite the problems.', note: 'meet a deadline / miss a deadline.' },
  { id: 'co06', cat: 'col', front: 'The manager ___ responsibility for the mistake.', back: 'The manager *took* responsibility for the mistake.' },
  { id: 'co07', cat: 'col', front: 'We\'ve finally ___ an agreement with the supplier.', back: 'We\'ve finally *reached* an agreement with the supplier.', note: 'reach an agreement / a decision / a conclusion.' },
  { id: 'co08', cat: 'col', front: 'It\'s important to ___ attention to detail.', back: 'It\'s important to *pay* attention to detail.' },
  { id: 'co09', cat: 'col', front: 'He ___ a good impression on the interviewers.', back: 'He *made* a good impression on the interviewers.' },
  { id: 'co10', cat: 'col', front: 'I\'d like to ___ some research before deciding.', back: 'I\'d like to *do* some research before deciding.' },
  { id: 'co11', cat: 'col', front: 'The company ___ a big risk by entering that market.', back: 'The company *took* a big risk by entering that market.' },
  { id: 'co12', cat: 'col', front: 'We need to ___ the gap between theory and practice.', back: 'We need to *bridge* the gap between theory and practice.' },
  { id: 'co13', cat: 'col', front: 'Prices have risen ___ (= a lot and quickly) since last year.', back: 'Prices have risen *sharply* since last year.', note: 'rise / fall sharply, steadily, slightly.' },
  { id: 'co14', cat: 'col', front: 'She made a ___ (= very convincing) case for the new strategy.', back: 'She made a *compelling* / *strong* case for the new strategy.' },
  { id: 'co15', cat: 'col', front: 'There\'s a ___ (= very small) chance we\'ll finish today.', back: 'There\'s a *slim* chance we\'ll finish today.' },
  { id: 'co16', cat: 'col', front: 'He\'s a ___ smoker (= smokes a lot).', back: 'He\'s a *heavy* smoker.', note: 'heavy rain, heavy traffic, heavy smoker.' },
  { id: 'co17', cat: 'col', front: 'We had an ___ discussion (= detailed) about the budget.', back: 'We had an *in-depth* discussion about the budget.' },
  { id: 'co18', cat: 'col', front: 'It\'s ___ important (= extremely) that we finish on time.', back: 'It\'s *vitally* / *crucially* important that we finish on time.' },
  { id: 'co19', cat: 'col', front: 'I\'m ___ aware of the risks.', back: 'I\'m *fully* / *well* aware of the risks.' },
  { id: 'co20', cat: 'col', front: 'The meeting will ___ place in Room 3.', back: 'The meeting will *take* place in Room 3.' },
  { id: 'co21', cat: 'col', front: 'We need to ___ the problem before it gets worse.', back: 'We need to *address* / *tackle* the problem before it gets worse.' },
  { id: 'co22', cat: 'col', front: 'They ___ a survey of 500 customers.', back: 'They *carried out* / *conducted* a survey of 500 customers.' },
  { id: 'co23', cat: 'col', front: 'Can you ___ an eye on my laptop for a minute?', back: 'Can you *keep* an eye on my laptop for a minute?' },
  { id: 'co24', cat: 'col', front: 'Let\'s ___ a break and continue in ten minutes.', back: 'Let\'s *take* a break and continue in ten minutes.' },
  { id: 'co25', cat: 'col', front: 'We need to ___ costs down this year.', back: 'We need to *keep* costs down this year.' },
  { id: 'co26', cat: 'col', front: 'The results ___ the need for more training.', back: 'The results *highlight* the need for more training.' },
  { id: 'co27', cat: 'col', front: 'The plan ___ with strong opposition.', back: 'The plan *met* with strong opposition.' },
  { id: 'co28', cat: 'col', front: 'It ___ sense to wait until next month.', back: 'It *makes* sense to wait until next month.' },
  { id: 'co29', cat: 'col', front: 'She ___ all her goals for the year.', back: 'She *achieved* all her goals for the year.', note: 'achieve / reach / meet a goal.' },
  { id: 'co30', cat: 'col', front: 'This decision could ___ serious consequences.', back: 'This decision could *have* serious consequences.' },
  { id: 'co31', cat: 'col', front: 'I\'m trying to ___ a balance between work and family.', back: 'I\'m trying to *strike* a balance between work and family.' },
  { id: 'co32', cat: 'col', front: 'Please ___ into account that prices may change.', back: 'Please *take* into account that prices may change.' },

  // ---------- PHRASAL VERBS ----------
  { id: 'pv01', cat: 'pv', front: 'We need to (postpone) the meeting until Monday.', back: 'We need to *put off* the meeting until Monday.' },
  { id: 'pv02', cat: 'pv', front: 'Can you (investigate) the issue?', back: 'Can you *look into* the issue?' },
  { id: 'pv03', cat: 'pv', front: 'They (cancelled) the event because of the rain.', back: 'They *called off* the event because of the rain.' },
  { id: 'pv04', cat: 'pv', front: 'I\'ll (discover) what happened.', back: 'I\'ll *find out* what happened.' },
  { id: 'pv05', cat: 'pv', front: 'The company (established) a new office in Madrid.', back: 'The company *set up* a new office in Madrid.' },
  { id: 'pv06', cat: 'pv', front: 'I can\'t (tolerate) this noise any more.', back: 'I can\'t *put up with* this noise any more.' },
  { id: 'pv07', cat: 'pv', front: 'She (mentioned) an interesting point in the meeting.', back: 'She *brought up* an interesting point in the meeting.' },
  { id: 'pv08', cat: 'pv', front: 'We (have no more) paper for the printer.', back: 'We\'ve *run out of* paper for the printer.' },
  { id: 'pv09', cat: 'pv', front: 'I (met by chance) an old colleague at the airport.', back: 'I *ran into* an old colleague at the airport.' },
  { id: 'pv10', cat: 'pv', front: 'It took him weeks to (recover from) the flu.', back: 'It took him weeks to *get over* the flu.' },
  { id: 'pv11', cat: 'pv', front: 'Please (complete) this form.', back: 'Please *fill in* / *fill out* this form.' },
  { id: 'pv12', cat: 'pv', front: 'The deal (failed to happen) at the last minute.', back: 'The deal *fell through* at the last minute.' },
  { id: 'pv13', cat: 'pv', front: 'We need to (reduce) spending on travel.', back: 'We need to *cut back on* / *cut down on* spending on travel.' },
  { id: 'pv14', cat: 'pv', front: 'I don\'t know yet, but I\'ll (reply to you later).', back: 'I don\'t know yet, but I\'ll *get back to you*.' },
  { id: 'pv15', cat: 'pv', front: 'Let\'s (review) the main points again.', back: 'Let\'s *go over* the main points again.' },
  { id: 'pv16', cat: 'pv', front: 'He (invented) a brilliant solution.', back: 'He *came up with* a brilliant solution.' },
  { id: 'pv17', cat: 'pv', front: 'She (proposed) a new idea at the meeting.', back: 'She *put forward* a new idea at the meeting.' },
  { id: 'pv18', cat: 'pv', front: 'I (accepted) extra work this month.', back: 'I *took on* extra work this month.' },
  { id: 'pv19', cat: 'pv', front: 'Don\'t (stop trying)! You\'re almost there.', back: 'Don\'t *give up*! You\'re almost there.' },
  { id: 'pv20', cat: 'pv', front: 'I\'ll (collect) you at the station at 8.', back: 'I\'ll *pick* you *up* at the station at 8.' },
  { id: 'pv21', cat: 'pv', front: 'Can you (wait) a second? I\'m on the phone.', back: 'Can you *hang on* / *hold on* a second? I\'m on the phone.' },
  { id: 'pv22', cat: 'pv', front: 'Sales (improved) in the last quarter.', back: 'Sales *picked up* in the last quarter.' },
  { id: 'pv23', cat: 'pv', front: 'We need to (include in our calculations) travel costs.', back: 'We need to *factor in* travel costs.' },
  { id: 'pv24', cat: 'pv', front: 'Let\'s (divide) the task into smaller steps.', back: 'Let\'s *break* the task *down* into smaller steps.' },
  { id: 'pv25', cat: 'pv', front: 'He really (resembles) his father.', back: 'He really *takes after* his father.' },
  { id: 'pv26', cat: 'pv', front: 'I need to (examine carefully) the contract.', back: 'I need to *go through* the contract.' },
  { id: 'pv27', cat: 'pv', front: 'The meeting (lasted longer than planned) by 20 minutes.', back: 'The meeting *ran over* by 20 minutes.' },
  { id: 'pv28', cat: 'pv', front: 'I can\'t (understand) what the problem is.', back: 'I can\'t *figure out* / *work out* what the problem is.' },
  { id: 'pv29', cat: 'pv', front: 'Please (continue) — don\'t let me interrupt you.', back: 'Please *carry on* / *go on* — don\'t let me interrupt you.' },
  { id: 'pv30', cat: 'pv', front: 'The project (was discovered to be) more complex than expected.', back: 'The project *turned out* to be more complex than expected.' },

  // ---------- LINKERS & TONE (hedging / politeness) ----------
  { id: 'lk01', cat: 'link', front: 'The plan is expensive. ___, it\'s our best option.', back: 'The plan is expensive. *However* / *Nevertheless*, it\'s our best option.' },
  { id: 'lk02', cat: 'link', front: '___ the rain, we went out. (+ noun)', back: '*Despite* / *In spite of* the rain, we went out.', note: 'despite + noun / -ing, never + clause.' },
  { id: 'lk03', cat: 'link', front: '___ it was raining, we went out. (+ clause)', back: '*Although* / *Even though* it was raining, we went out.' },
  { id: 'lk04', cat: 'link', front: 'Sales rose in Spain, ___ they fell in France.', back: 'Sales rose in Spain, *whereas* / *while* they fell in France.' },
  { id: 'lk05', cat: 'link', front: 'We missed the deadline. ___ (= because of this), we lost the client.', back: 'We missed the deadline. *Consequently* / *As a result*, we lost the client.' },
  { id: 'lk06', cat: 'link', front: 'The system is faster. ___ (= also), it\'s cheaper.', back: 'The system is faster. *Moreover* / *Furthermore* / *What\'s more*, it\'s cheaper.' },
  { id: 'lk07', cat: 'link', front: '___ (= to sum up), the results were positive.', back: '*Overall* / *All in all* / *In short*, the results were positive.' },
  { id: 'lk08', cat: 'link', front: 'He isn\'t the strongest candidate. ___, he has a lot of experience.', back: 'He isn\'t the strongest candidate. *That said* / *Having said that*, he has a lot of experience.' },
  { id: 'lk09', cat: 'link', front: 'Soften it: "You\'re wrong."', back: '"I\'m not sure that\'s *quite* right." / "I see it *slightly* differently."' },
  { id: 'lk10', cat: 'link', front: 'Soften it: "This is a bad idea."', back: '"I\'m not *convinced* this is the best approach."' },
  { id: 'lk11', cat: 'link', front: 'Hedge it: "The data proves that customers prefer option A."', back: '"The data *suggests* / *seems to indicate* that customers prefer option A."' },
  { id: 'lk12', cat: 'link', front: 'Soften it: "We can\'t do it."', back: '"*I\'m afraid* that *might be* difficult."' },
  { id: 'lk13', cat: 'link', front: 'Make it polite: "Send me the report."', back: '"*Would you mind* sending me the report?" / "*Could you* send me the report *when you get a chance*?"' },
  { id: 'lk14', cat: 'link', front: 'Make it polite: "I want a pay rise."', back: '"*I was wondering if* we could discuss my salary."' },
  { id: 'lk15', cat: 'link', front: '___ (= talking about) the budget, we\'re on track.', back: '*In terms of* / *Regarding* / *As regards* the budget, we\'re on track.' },
  { id: 'lk16', cat: 'link', front: '___, this is the best solution. (= it can be argued that)', back: '*Arguably*, this is the best solution.' },
  { id: 'lk17', cat: 'link', front: 'We\'ll launch in May, ___ (= only if) the tests are successful.', back: 'We\'ll launch in May, *provided that* / *as long as* the tests are successful.' },
  { id: 'lk18', cat: 'link', front: '___ we act now, we\'ll lose the contract. (= if we don\'t)', back: '*Unless* we act now, we\'ll lose the contract.' },
  { id: 'lk19', cat: 'link', front: 'He speaks French, ___ (= and also, which is even more impressive) German and Italian.', back: 'He speaks French, *not to mention* German and Italian.' },
  { id: 'lk20', cat: 'link', front: 'We expected problems, but ___ (= in the end, surprisingly), everything went smoothly.', back: 'We expected problems, but *as it turned out*, everything went smoothly.' },
  { id: 'lk21', cat: 'link', front: 'Give 3 C1 alternatives to "I think…"', back: '*It seems to me that…* / *From my perspective…* / *I\'d argue that…*' },
  { id: 'lk22', cat: 'link', front: 'We worked overtime ___ (= with the purpose of) meet the deadline.', back: 'We worked overtime *in order to* / *so as to* meet the deadline.' },
  { id: 'lk23', cat: 'link', front: 'The results were good; ___, there\'s room for improvement.', back: 'The results were good; *even so* / *nonetheless*, there\'s room for improvement.' },

  // ---------- GRAMÁTICA C1 ----------
  { id: 'gr01', cat: 'gram', front: 'I have never seen such a mess. → Never…', back: '*Never have I seen* such a mess.', note: 'Negative adverb at the start → inversion (formal/emphatic).' },
  { id: 'gr02', cat: 'gram', front: 'He was late and he also forgot the documents. → Not only…', back: '*Not only was he* late, but he also forgot the documents.' },
  { id: 'gr03', cat: 'gram', front: 'As soon as I arrived, the meeting started. → No sooner…', back: '*No sooner had I arrived than* the meeting started.' },
  { id: 'gr04', cat: 'gram', front: 'If I had known, I would have called you. → Had…', back: '*Had I known*, I would have called you.' },
  { id: 'gr05', cat: 'gram', front: 'If you have any questions, contact me. → Should…', back: '*Should you have* any questions, please contact me.', note: 'Very common in formal emails.' },
  { id: 'gr06', cat: 'gram', front: 'I need more time. → What…', back: '*What I need is* more time.', note: 'Cleft sentence: puts emphasis on the key information.' },
  { id: 'gr07', cat: 'gram', front: 'John sent the email, not Mary. → It was…', back: '*It was John who* sent the email.' },
  { id: 'gr08', cat: 'gram', front: 'I didn\'t study, so now I don\'t have a C1. → If…', back: '*If I had studied, I would have* a C1 now.', note: 'Mixed conditional: past cause → present result.' },
  { id: 'gr09', cat: 'gram', front: 'I\'m not organised, so I missed the deadline. → If…', back: '*If I were more organised, I wouldn\'t have missed* the deadline.', note: 'Mixed conditional: present situation → past result.' },
  { id: 'gr10', cat: 'gram', front: 'I regret not accepting the job. → I wish…', back: '*I wish I had accepted* the job.' },
  { id: 'gr11', cat: 'gram', front: 'People say that he is very rich. → He…', back: '*He is said to be* very rich.' },
  { id: 'gr12', cat: 'gram', front: 'People believe that the company lost money. → The company…', back: '*The company is believed to have lost* money.' },
  { id: 'gr13', cat: 'gram', front: 'Because I didn\'t know the answer, I stayed quiet. → Not…', back: '*Not knowing* the answer, I stayed quiet.' },
  { id: 'gr14', cat: 'gram', front: 'After he had finished the report, he went home. → Having…', back: '*Having finished* the report, he went home.' },
  { id: 'gr15', cat: 'gram', front: 'It\'s possible that she missed the train. → She might…', back: 'She *might have missed* the train.' },
  { id: 'gr16', cat: 'gram', front: 'I\'m sure he didn\'t see the message. → He can\'t…', back: 'He *can\'t have seen* the message.' },
  { id: 'gr17', cat: 'gram', front: 'It wasn\'t necessary to bring food, but I did. → I needn\'t…', back: 'I *needn\'t have brought* food.' },
  { id: 'gr18', cat: 'gram', front: 'It\'s a pity we didn\'t book earlier. → We should…', back: 'We *should have booked* earlier.' },
  { id: 'gr19', cat: 'gram', front: 'I prefer you not to call me at night. → I\'d rather…', back: '*I\'d rather you didn\'t call* me at night.' },
  { id: 'gr20', cat: 'gram', front: 'We should leave now. → It\'s high time…', back: '*It\'s high time we left*.' },
  { id: 'gr21', cat: 'gram', front: 'A technician repaired my laptop. → I had…', back: '*I had my laptop repaired*.', note: 'Causative: have/get + object + past participle.' },
  { id: 'gr22', cat: 'gram', front: 'He didn\'t realise the danger at all. → Little…', back: '*Little did he realise* the danger.' },
  { id: 'gr23', cat: 'gram', front: 'I understood it only when I read it again. → Only when…', back: '*Only when I read it again did I understand* it.' },
  { id: 'gr24', cat: 'gram', front: 'It doesn\'t matter how hard it is, we\'ll do it. → However…', back: '*However hard it is*, we\'ll do it.' },

  // ---------- WORK ENGLISH ----------
  { id: 'wk01', cat: 'work', front: '(Email) You\'re writing again after your previous email.', back: '*Further to my previous email*, … / *I\'m following up on* my last email.' },
  { id: 'wk02', cat: 'work', front: '(Email) You\'re sending a file.', back: '*Please find attached* the report. / *I\'ve attached* the report.' },
  { id: 'wk03', cat: 'work', front: '(Email) Closing: you expect a reply.', back: '*I look forward to hearing from you.*' },
  { id: 'wk04', cat: 'work', front: '(Email) You\'re replying late.', back: '*Apologies for the delayed response.*' },
  { id: 'wk05', cat: 'work', front: '(Meeting) You want to interrupt politely.', back: '*Sorry to interrupt, but could I just add something?*' },
  { id: 'wk06', cat: 'work', front: '(Meeting) You didn\'t understand something.', back: '*Sorry, could you clarify what you mean by…?*' },
  { id: 'wk07', cat: 'work', front: '(Meeting) You check you understood correctly.', back: '*So, if I understand correctly, you\'re saying that…*' },
  { id: 'wk08', cat: 'work', front: '(Meeting) You disagree politely.', back: '*I see your point, but I have some concerns about…*' },
  { id: 'wk09', cat: 'work', front: '(Meeting) You move to the next topic.', back: '*Let\'s move on to the next item on the agenda.*' },
  { id: 'wk10', cat: 'work', front: '(Meeting) You summarise at the end.', back: '*To wrap up, we\'ve agreed that…*' },
  { id: 'wk11', cat: 'work', front: '(Any situation) You need a few seconds to think.', back: '*That\'s a good question. Let me think about that for a second.*' },
  { id: 'wk12', cat: 'work', front: '(Interview) You talk about a strength with evidence.', back: '*One of my key strengths is… For example, in my last role I…*' },
  { id: 'wk13', cat: 'work', front: '(Interview) You talk about a weakness positively.', back: '*Something I\'ve been working on is… so I\'ve started…*' },
  { id: 'wk14', cat: 'work', front: '(Interview) "Why do you want this job?"', back: '*I\'m keen to take on more responsibility, and I believe my experience in… would add value to your team.*' },
  { id: 'wk15', cat: 'work', front: '(Interview) You describe an achievement with numbers.', back: '*I led a project that reduced costs by 15% in six months.*' },
  { id: 'wk16', cat: 'work', front: '(Call) You can\'t hear the other person well.', back: '*Sorry, you\'re breaking up. Could you say that again?*' },
  { id: 'wk17', cat: 'work', front: '(Deadline) You need more time.', back: '*Would it be possible to extend the deadline to Friday?*' },
  { id: 'wk18', cat: 'work', front: '(Negotiation) You make a conditional offer.', back: '*If you can commit to a two-year contract, we could offer a 10% discount.*' },
  { id: 'wk19', cat: 'work', front: '(Update) The project is going well / a bit late.', back: '*We\'re on track to finish by the end of the month.* / *We\'re slightly behind schedule because…*' },
  { id: 'wk20', cat: 'work', front: '(Delegating) You ask someone to do a task.', back: '*Would you be able to take care of…?* / *Could you handle…?*' },
  { id: 'wk21', cat: 'work', front: '(Small talk) Starting a video call.', back: '*How\'s your week going so far?*' },
  { id: 'wk22', cat: 'work', front: '(Meeting) Closing the meeting.', back: '*Thanks, everyone. I\'ll send round a summary later today.*' },
  { id: 'wk23', cat: 'work', front: '(Presentation) Referring to a chart.', back: '*As you can see from this chart, …*' },
  { id: 'wk24', cat: 'work', front: '(Feedback) You ask for someone\'s opinion on your work.', back: '*I\'d really appreciate your feedback on…*' },
  { id: 'wk25', cat: 'work', front: '(Email) A gentle reminder.', back: '*Just a quick reminder about…* / *I\'m just checking in on…*' },
];

// ---------- MISIONES PARA PENSAR EN INGLÉS (fuera de la app) ----------
const SELFTALK_MISSIONS = [
  'While making breakfast, narrate every step out loud.',
  'On your way to work, describe what you see: people, buildings, the weather.',
  'Plan your day out loud: priorities, times and tasks.',
  'Explain to an imaginary colleague what you did yesterday at work (past tenses!).',
  'While training, describe each exercise and how it feels.',
  'Replay a conversation you had today in Spanish or Catalan — but in English.',
  'Describe the room you are in with as many details as possible.',
  'Talk about how you feel today and why. Avoid "good" and "bad": find better adjectives.',
  'Give yourself instructions while cooking dinner.',
  'Comment on today\'s news as if you were a TV presenter for 2 minutes.',
  'Imagine you are a tour guide in your neighbourhood.',
  'Think of three things you are grateful for and explain why.',
  'Every time you don\'t know a word today, describe it instead of translating it.',
  'Before sleeping, review your day in your head — only in English.',
  'Argue both sides of a decision you need to make.',
  'While shopping, narrate what you need, compare prices and explain your choices.',
  'Prepare out loud what you want to say in your next speaking session.',
  'During a 10-minute walk, only English is allowed in your head.',
  'Explain your job to a 10-year-old.',
  'Describe a photo on your phone as if the listener couldn\'t see it.',
];
